image: node:8-alpine

cache:
    paths:
        - node_modules/

stages:
    - lint
    - build
    - deploy

lint:
    stage: lint
    script:
        - yarn
        - yarn run lint

build:
    stage: build
    script:
        - yarn
        - yarn run build

deploy:
    stage: deploy
    when: manual
    only:
        - master
    script:
        - apk add --update git openssh-client
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -p 2222 -H 'warcraftjournal.org' >> ~/.ssh/known_hosts
        - echo -e 'Host warcraftjournal.org\n    Port 2222' >> ~/.ssh/config
        - git push dokku@warcraftjournal.org:warcraftjournal-staging master
    environment:
        name: staging
        url: https://staging.warcraftjournal.org
