image: node:8-alpine

cache:
    paths:
        - node_modules/

stages:
    - lint
    - build
    - deploy

lint:
    stage: lint
    script:
        - yarn
        - yarn run lint

build:
    stage: build
    script:
        - yarn
        - yarn run build

deploy:
    stage: deploy
    when: manual
    script:
        - apk add --update openssh-client
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -H 'warcraftjournal.org' >> ~/.ssh/known_hosts
        - git push dokku@warcraftjournal.org:warcraftjournal-staging master