stages:
    - lint
    - build
    - deploy

lint:
    image: node:8-alpine
    stage: lint
    cache:
        paths:
            - node_modules/
    script:
        - yarn
        - yarn run lint

build:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8} --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA:0:8} .
        - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}
