image: node:8-alpine

cache:
    paths:
        - node_modules/

before_script:
    - yarn

stages:
    - lint
    - build

lint:
    stage: lint
    script:
        - yarn run lint

build:
    stage: build
    script:
        - yarn run build
